sudo: true

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e git+https://github.com/peteut/nose2-cprof.git#egg=nose2cprof
  - pip install -e .

script:
  - make test
